### ISSUE TITLE
Driver [debug] not supported

### ISSUE THREAD

**Issue by atefBB** [laravelflare/mail-debug#1]
Hi, I get this message «Driver [debug] not supported» when I try to implement your solution, Ideas?

**Comment by AdenFraser** [comment]
Have you definitely added the Service Provider to your Application config?

**Comment by AdenFraser** [comment]
Are you still having this issue? If so please could you provide more details so that I can debug and provide a fix.

Otherwise, please close :)

**Comment by atefBB** [comment]
Yes, I do, but I still having the same error. Should I have some config in the file 'mail-debug.php'? or in 'mail.php'?

**Comment by AdenFraser** [comment]
mail-debug.php should have been created and populated by vendor:publish.

What Laravel version are you running?

**Comment by atefBB** [comment]
I'm using laravel 5.1, mail-debug.php is there.

**Comment by AdenFraser** [comment]
Could you provide a full stack trace? And a list of any other packages you have installed?

I'll investigate further :)

**Comment by atefBB** [comment]
I have those packages installed in my project:
"bugsnag/bugsnag-laravel": "1._",
        "ramsey/uuid": "~2.8",
        "guzzlehttp/guzzle": "~5.0",
        "illuminate/html": "~5.0",
        "doctrine/dbal": "~2.5",
        "maknz/slack": "~1.5",
        "lucadegasperi/oauth2-server-laravel": "4.0.x@dev",
        "caouecs/laravel4-lang": "~2.0",
        "pusher/pusher-php-server": "~2.0",
        "vinkla/pusher": "^2.2",
        "laravolt/avatar": "~0.3",
        "guidovanbiemen/laravel-whoops": "^1.0",
        "themsaid/laravel-mail-preview": "^1.1",
        "messaged/php-mime-mail-parser": "^1.0",
        "themsaid/laravel-langman": "^1.1",
        "barryvdh/laravel-translation-manager": "^0.2.1",
        "laravelflare/mail-debug": "^1.0"
and : 
"phpunit/phpunit": "~4.4.0",
        "phpspec/phpspec": "~2.1",
        "laracasts/testdummy": "~2.3",
        "mockery/mockery": "0.9._".
Thanks.
